import { useEffect, useRef, useState, type FormEvent } from 'react';
import { Html5Qrcode } from 'html5-qrcode';
import { api, type Guest } from '../api';
import { StatusBadge, isAutoGeneratedVoucherCode } from '../components/StatusBadge';

const QR_READER_ELEMENT_ID = 'qr-reader';

export function CheckInPage() {
  const [email, setEmail] = useState('');
  const [results, setResults] = useState<Guest[]>([]);
  const [selected, setSelected] = useState<Guest | null>(null);
  const [searched, setSearched] = useState(false);
  const [loading, setLoading] = useState(false);
  const [sending, setSending] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [scanning, setScanning] = useState(false);
  const [scanError, setScanError] = useState<string | null>(null);
  const [lastScannedValue, setLastScannedValue] = useState<string | null>(null);
  const scannerRef = useRef<Html5Qrcode | null>(null);

  useEffect(() => {
    if (!scanning) return;

    const scanner = new Html5Qrcode(QR_READER_ELEMENT_ID);
    scannerRef.current = scanner;
    let cancelled = false;

    scanner
      .start(
        { facingMode: 'environment' },
        { fps: 10, qrbox: { width: 250, height: 250 } },
        async (decodedText) => {
          if (cancelled) return;
          cancelled = true;
          await stopScanner();
          await handleQrScanned(decodedText);
        },
        () => {
          // Per-frame decode failures are expected while the camera is searching for a code; ignore them.
        }
      )
      .catch((err) => {
        setScanError(err instanceof Error ? err.message : 'Could not access the camera');
        setScanning(false);
      });

    return () => {
      cancelled = true;
      stopScanner();
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [scanning]);

  async function stopScanner() {
    const scanner = scannerRef.current;
    scannerRef.current = null;
    if (scanner) {
      try {
        await scanner.stop();
        scanner.clear();
      } catch {
        // Scanner may already be stopped; safe to ignore.
      }
    }
  }

  async function handleQrScanned(decodedText: string) {
    setScanning(false);
    setScanError(null);
    setError(null);
    setLoading(true);
    const scannedValue = decodedText.trim();
    setLastScannedValue(scannedValue);
    try {
      const guest = await api.lookupGuestByQr(scannedValue);
      setSelected(guest);
      setResults([guest]);
      setSearched(true);
      setLastScannedValue(null);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'No guest matches that QR code');
    } finally {
      setLoading(false);
    }
  }

  async function handleSearch(e: FormEvent) {
    e.preventDefault();
    if (!email.trim()) return;
    setLoading(true);
    setError(null);
    setSelected(null);
    setLastScannedValue(null);
    try {
      const guests = await api.lookupGuestsByEmail(email.trim());
      setResults(guests);
      setSearched(true);
      if (guests.length === 1) setSelected(guests[0]);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Search failed');
    } finally {
      setLoading(false);
    }
  }

  async function handleSend() {
    if (!selected) return;
    setSending(true);
    setError(null);
    try {
      const updated = await api.sendVoucher(selected.id);
      setSelected(updated);
      setResults((prev) => prev.map((g) => (g.id === updated.id ? updated : g)));
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to send voucher');
    } finally {
      setSending(false);
    }
  }

  return (
    <div className="max-w-xl mx-auto">
      <h2 className="text-xl font-semibold mb-4">Guest Arrival Check-In</h2>
      <form onSubmit={handleSearch} className="flex gap-2 mb-4">
        <input
          type="text"
          placeholder="Guest email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          className="flex-1 border rounded-lg px-3 py-2"
        />
        <button type="submit" className="bg-gray-900 text-white px-4 py-2 rounded-lg" disabled={loading}>
          {loading ? 'Searching...' : 'Search'}
        </button>
      </form>

      <div className="mb-4">
        <button
          onClick={() => {
            setScanError(null);
            setScanning((prev) => !prev);
          }}
          className="w-full border border-gray-900 text-gray-900 px-4 py-2 rounded-lg font-medium"
        >
          {scanning ? 'Cancel Scan' : 'Scan QR Code'}
        </button>
        {scanning && <div id={QR_READER_ELEMENT_ID} className="mt-3 rounded-lg overflow-hidden" />}
        {scanError && <p className="text-red-600 mt-2 text-sm">{scanError}</p>}
      </div>

      {error && (
        <div className="mb-4">
          <p className="text-red-600">{error}</p>
          {lastScannedValue && (
            <p className="text-xs text-gray-500 mt-1 break-all">
              Scanned value: <span className="font-mono">{lastScannedValue}</span>
            </p>
          )}
        </div>
      )}

      {results.length > 1 && !selected && (
        <ul className="divide-y border rounded-lg mb-4">
          {results.map((g) => (
            <li
              key={g.id}
              className="p-3 cursor-pointer hover:bg-gray-50 flex justify-between items-center"
              onClick={() => setSelected(g)}
            >
              <span>
                {g.name} — {g.email}
              </span>
              <StatusBadge status={g.sendStatus} />
            </li>
          ))}
        </ul>
      )}

      {searched && results.length === 0 && !loading && (
        <p className="text-gray-500">No guest found for that email.</p>
      )}

      {selected && (
        <div className="border rounded-xl p-5 space-y-3">
          <div className="flex justify-between items-start">
            <div>
              <p className="text-lg font-semibold">{selected.name}</p>
              <p className="text-gray-600">{selected.email}</p>
            </div>
            <StatusBadge status={selected.sendStatus} />
          </div>

          <div className="text-sm text-gray-600 space-y-1">
            <p>RSVP status: {selected.rsvpStatus || '—'}</p>
            <p>
              Voucher:{' '}
              {selected.voucher ? (
                isAutoGeneratedVoucherCode(selected.voucher.code) && selected.voucher.link ? (
                  <a href={selected.voucher.link} target="_blank" rel="noreferrer" className="text-blue-600 underline">
                    {selected.voucher.link}
                  </a>
                ) : (
                  selected.voucher.code
                )
              ) : (
                'Not yet assigned (next available will be used)'
              )}
            </p>
            {selected.lastSentAt && <p>Last sent: {new Date(selected.lastSentAt).toLocaleString()}</p>}
            {selected.lastError && <p className="text-red-600">Last error: {selected.lastError}</p>}
          </div>

          <button
            onClick={handleSend}
            disabled={sending}
            className="w-full bg-emerald-600 text-white py-2 rounded-lg font-medium disabled:opacity-50"
          >
            {sending ? 'Sending...' : selected.sendStatus === 'SENT' ? 'Resend Voucher' : 'Send Voucher'}
          </button>

          <button onClick={() => setSelected(null)} className="w-full text-gray-500 text-sm py-1">
            ← Back to search results
          </button>
        </div>
      )}
    </div>
  );
}
