import { useEffect, useState, type FormEvent } from 'react';
import { api, type Guest } from '../api';
import { StatusBadge, isAutoGeneratedVoucherCode } from '../components/StatusBadge';

export function GuestsPage() {
  const [guests, setGuests] = useState<Guest[]>([]);
  const [search, setSearch] = useState('');
  const [loading, setLoading] = useState(false);
  const [sendingId, setSendingId] = useState<string | null>(null);
  const [deletingId, setDeletingId] = useState<string | null>(null);
  const [deletingAll, setDeletingAll] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function load(term = search) {
    setLoading(true);
    setError(null);
    try {
      const data = await api.listGuests(term);
      setGuests(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to load guests');
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    load('');
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  async function handleSend(id: string) {
    setSendingId(id);
    setError(null);
    try {
      const updated = await api.sendVoucher(id);
      setGuests((prev) => prev.map((g) => (g.id === updated.id ? updated : g)));
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to send voucher');
    } finally {
      setSendingId(null);
    }
  }

  async function handleDelete(id: string, name: string) {
    if (!window.confirm(`Delete guest "${name}"? Their voucher (if any) goes back to the available pool.`)) return;
    setDeletingId(id);
    setError(null);
    try {
      await api.deleteGuest(id);
      setGuests((prev) => prev.filter((g) => g.id !== id));
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to delete guest');
    } finally {
      setDeletingId(null);
    }
  }

  async function handleDeleteAll() {
    if (guests.length === 0) return;
    if (
      !window.confirm(
        'Delete ALL guests in the system (not just this filtered view)? This cannot be undone. Any assigned vouchers go back to the available pool.'
      )
    )
      return;
    setDeletingAll(true);
    setError(null);
    try {
      await api.deleteAllGuests();
      setGuests([]);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to delete all guests');
    } finally {
      setDeletingAll(false);
    }
  }

  function handleSearchSubmit(e: FormEvent) {
    e.preventDefault();
    load(search);
  }

  return (
    <div className="max-w-4xl mx-auto">
      <h2 className="text-xl font-semibold mb-4">All Guests</h2>
      <form onSubmit={handleSearchSubmit} className="flex gap-2 mb-4">
        <input
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          placeholder="Search by name or email"
          className="flex-1 border rounded-lg px-3 py-2"
        />
        <button className="bg-gray-900 text-white px-4 py-2 rounded-lg">Search</button>
        <button
          type="button"
          onClick={handleDeleteAll}
          disabled={deletingAll || guests.length === 0}
          className="text-sm bg-red-50 text-red-700 px-4 py-2 rounded-lg disabled:opacity-50 whitespace-nowrap"
        >
          {deletingAll ? 'Deleting All...' : 'Delete All'}
        </button>
      </form>

      {error && <p className="text-red-600 mb-2">{error}</p>}
      {loading && <p className="text-gray-500">Loading...</p>}

      <div className="border rounded-xl overflow-x-auto">
        <table className="w-full text-sm table-fixed">
          <thead className="bg-gray-50 text-left">
            <tr>
              <th className="p-3 w-10">#</th>
              <th className="p-3 min-w-[120px] resize-x overflow-auto">Name</th>
              <th className="p-3 min-w-[200px] resize-x overflow-auto">Email</th>
              <th className="p-3 min-w-[220px] resize-x overflow-auto">Voucher</th>
              <th className="p-3 min-w-[110px] resize-x overflow-auto">Status</th>
              <th className="p-3 w-40"></th>
            </tr>
          </thead>
          <tbody>
            {guests.map((g, i) => (
              <tr key={g.id} className="border-t">
                <td className="p-3 text-gray-500">{i + 1}</td>
                <td className="p-3 truncate">{g.name}</td>
                <td className="p-3 truncate">{g.email}</td>
                <td className="p-3 truncate">
                  {g.voucher
                    ? isAutoGeneratedVoucherCode(g.voucher.code) && g.voucher.link
                      ? g.voucher.link
                      : g.voucher.code
                    : '—'}
                </td>
                <td className="p-3">
                  <StatusBadge status={g.sendStatus} />
                </td>
                <td className="p-3 text-right whitespace-nowrap">
                  <button
                    onClick={() => handleSend(g.id)}
                    disabled={sendingId === g.id}
                    className="text-sm bg-emerald-600 text-white px-3 py-1 rounded-lg disabled:opacity-50"
                  >
                    {sendingId === g.id ? 'Sending...' : g.sendStatus === 'SENT' ? 'Resend' : 'Send'}
                  </button>
                  <button
                    onClick={() => handleDelete(g.id, g.name)}
                    disabled={deletingId === g.id}
                    className="text-sm bg-red-50 text-red-700 px-3 py-1 rounded-lg ml-2 disabled:opacity-50"
                  >
                    {deletingId === g.id ? 'Deleting...' : 'Delete'}
                  </button>
                </td>
              </tr>
            ))}
            {guests.length === 0 && !loading && (
              <tr>
                <td colSpan={6} className="p-4 text-center text-gray-500">
                  No guests yet. Import a list to get started.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}
