import { useEffect, useState } from 'react';
import { api, type Voucher } from '../api';
import { isAutoGeneratedVoucherCode } from '../components/StatusBadge';

export function VouchersPage() {
  const [vouchers, setVouchers] = useState<Voucher[]>([]);
  const [loading, setLoading] = useState(false);
  const [deletingId, setDeletingId] = useState<string | null>(null);
  const [deletingAll, setDeletingAll] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function load() {
    setLoading(true);
    setError(null);
    try {
      setVouchers(await api.listVouchers());
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to load vouchers');
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    load();
  }, []);

  async function handleDelete(id: string) {
    if (!window.confirm('Delete this voucher? If it was assigned, the guest goes back to "not yet assigned".')) return;
    setDeletingId(id);
    setError(null);
    try {
      await api.deleteVoucher(id);
      setVouchers((prev) => prev.filter((v) => v.id !== id));
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to delete voucher');
    } finally {
      setDeletingId(null);
    }
  }

  async function handleDeleteAll() {
    if (vouchers.length === 0) return;
    if (
      !window.confirm(
        `Delete ALL ${vouchers.length} vouchers? This cannot be undone. Guests they were assigned to go back to "not yet assigned".`
      )
    )
      return;
    setDeletingAll(true);
    setError(null);
    try {
      await api.deleteAllVouchers();
      setVouchers([]);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to delete all vouchers');
    } finally {
      setDeletingAll(false);
    }
  }

  const assignedCount = vouchers.filter((v) => v.status === 'ASSIGNED').length;
  const availableCount = vouchers.length - assignedCount;

  return (
    <div className="max-w-4xl mx-auto">
      <div className="flex items-center justify-between mb-4">
        <h2 className="text-xl font-semibold">All Vouchers</h2>
        <div className="flex gap-3">
          <button onClick={load} className="text-sm text-gray-600 hover:underline">
            Refresh
          </button>
          <button
            onClick={handleDeleteAll}
            disabled={deletingAll || vouchers.length === 0}
            className="text-sm bg-red-50 text-red-700 px-3 py-1 rounded-lg disabled:opacity-50"
          >
            {deletingAll ? 'Deleting All...' : 'Delete All'}
          </button>
        </div>
      </div>

      <div className="grid grid-cols-3 gap-3 mb-4">
        <div className="border rounded-xl p-4 text-center">
          <p className="text-2xl font-bold">{vouchers.length}</p>
          <p className="text-xs text-gray-500">Total vouchers</p>
        </div>
        <div className="border rounded-xl p-4 text-center">
          <p className="text-2xl font-bold text-emerald-700">{assignedCount}</p>
          <p className="text-xs text-gray-500">Assigned to a guest</p>
        </div>
        <div className="border rounded-xl p-4 text-center">
          <p className="text-2xl font-bold text-amber-700">{availableCount}</p>
          <p className="text-xs text-gray-500">Available (spare)</p>
        </div>
      </div>

      {error && <p className="text-red-600 mb-2">{error}</p>}
      {loading && <p className="text-gray-500">Loading...</p>}

      <div className="border rounded-xl overflow-x-auto">
        <table className="w-full text-sm table-fixed">
          <thead className="bg-gray-50 text-left">
            <tr>
              <th className="p-3 w-10">#</th>
              <th className="p-3 min-w-[260px] resize-x overflow-auto">Voucher</th>
              <th className="p-3 min-w-[110px] resize-x overflow-auto">Status</th>
              <th className="p-3 min-w-[220px] resize-x overflow-auto">Assigned to</th>
              <th className="p-3 w-24"></th>
            </tr>
          </thead>
          <tbody>
            {vouchers.map((v, i) => (
              <tr key={v.id} className="border-t">
                <td className="p-3 text-gray-500">{i + 1}</td>
                <td className="p-3 truncate">
                  {isAutoGeneratedVoucherCode(v.code) && v.link ? v.link : v.code}
                </td>
                <td className="p-3">
                  <span
                    className={`inline-block px-2 py-1 rounded-full text-xs font-medium ${
                      v.status === 'ASSIGNED' ? 'bg-emerald-100 text-emerald-800' : 'bg-amber-100 text-amber-800'
                    }`}
                  >
                    {v.status === 'ASSIGNED' ? 'Assigned' : 'Available'}
                  </span>
                </td>
                <td className="p-3 truncate">{v.guest ? `${v.guest.name} (${v.guest.email})` : '—'}</td>
                <td className="p-3 text-right">
                  <button
                    onClick={() => handleDelete(v.id)}
                    disabled={deletingId === v.id}
                    className="text-sm bg-red-50 text-red-700 px-3 py-1 rounded-lg disabled:opacity-50"
                  >
                    {deletingId === v.id ? 'Deleting...' : 'Delete'}
                  </button>
                </td>
              </tr>
            ))}
            {vouchers.length === 0 && !loading && (
              <tr>
                <td colSpan={5} className="p-4 text-center text-gray-500">
                  No vouchers yet. Import a list or add one manually on the Import tab.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}
