import type { Guest } from '../api';

// Codes we auto-generate on import for link-only vouchers (see backend generateVoucherCode) aren't meaningful to a guest.
const AUTO_GENERATED_CODE_PATTERN = /^VCH-[0-9A-F]{8}$/;

export function isAutoGeneratedVoucherCode(code: string): boolean {
  return AUTO_GENERATED_CODE_PATTERN.test(code);
}

const STYLES: Record<Guest['sendStatus'], string> = {
  NOT_SENT: 'bg-gray-100 text-gray-700',
  SENDING: 'bg-yellow-100 text-yellow-800',
  SENT: 'bg-green-100 text-green-800',
  FAILED: 'bg-red-100 text-red-800',
};

const LABELS: Record<Guest['sendStatus'], string> = {
  NOT_SENT: 'Not sent',
  SENDING: 'Sending...',
  SENT: 'Sent',
  FAILED: 'Failed',
};

export function StatusBadge({ status }: { status: Guest['sendStatus'] }) {
  return (
    <span className={`inline-block px-2 py-1 rounded-full text-xs font-medium ${STYLES[status]}`}>
      {LABELS[status]}
    </span>
  );
}
